# Generated by Django 2.0.7 on 2018-07-06 12:03

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentJson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2018, 7, 6, 12, 3, 37, 743248))),
                ('name', models.CharField(max_length=100)),
                ('json_data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
