# Generated by Django 2.0.7 on 2018-07-06 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0003_auto_20180706_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentjson',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 7, 6, 12, 51, 7, 17106)),
        ),
    ]
