# Generated by Django 2.0.7 on 2018-07-06 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0004_auto_20180706_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThumbnailData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail_name', models.CharField(max_length=200)),
                ('thumbnail_title', models.CharField(max_length=200)),
                ('thumbnail_content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='componentjson',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 7, 6, 13, 22, 31, 966768)),
        ),
    ]
