# Generated by Django 2.0.7 on 2018-07-06 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_app', '0005_auto_20180706_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentjson',
            name='site_thumb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='componentjson',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 7, 6, 18, 47, 57, 148994), null=True),
        ),
        migrations.AlterField(
            model_name='componentjson',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='thumbnaildata',
            name='thumbnail_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thumbnaildata',
            name='thumbnail_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='thumbnaildata',
            name='thumbnail_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
